src/config/homestead.json

Modify token whitelist per proposal: https://forum.balancer.finance/t/bal-whitelist-round-6/156
- Remove LEV, PRO
- Add ALEPH, ARPA, ARTE, CARD, CUR, KAI, NEC, uDOO

BAL Whitelist - Round 6

---

src/components/List/Token.vue
src/components/Modal/SelectToken.vue
src/components/Sidebar.vue
src/store/modules/price.ts
src/store/modules/subgraph.ts
src/store/modules/ui.ts
src/views/Create.vue

Remove coingecko pricing, keep only in pool creation for unknown tokens

Remove coingecko pricing

---

package-lock.json
package.json
src/components/Form/Wrapper.vue
src/components/Message/Checkbox.vue
src/components/Message/SimilarPools.vue
src/components/Message/Slippage.vue
src/components/Message/WarningRateChange.vue
src/components/Modal/AddLiquidity.vue
src/components/Modal/RemoveLiquidity.vue
src/components/PoolOverview.vue
src/components/Ui/Modal.vue
src/helpers/validation.ts
src/vars.scss
src/views/Create.vue
src/views/Pool.vue

* Add loading state to button in Create view
* Redirect to Setup view if no proxy found
* Add loading state to Wrap/Unwrap buttons
* Add validation for Wrapper inputs
* Hide pool action buttons when web3 not connected
* Add message to Checkbox
* Bump @walletconnect/web3-provider
* Hide MessageSimilarPools for private pools
* Add $info style var
* Add Slippage message
* Cut Pie from PoolOverview
* Add Icon to Slippage message
* Decrease vertical margin for several messages
* Increase max-height for UiModal
* Move messages inside Add/Remove modal body
Fixes # .
- 
- 
-

Merge upstream

---

src/components/List/Token.vue
src/components/Modal/PoolCreation.vue
src/components/Modal/SelectToken.vue
src/components/Sidebar.vue
src/store/modules/price.ts
src/store/modules/ui.ts
src/views/Create.vue

Took a deeper look at pricing, and the problem is even bigger than I expected:
<details>
<summary>Subgraph prices</summary>
```javascript
{
'0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2': 383.2390778313332,
'0xba100000625a3754423978a60c9317c58a424e3D': 20.447459976116345,
'0x6B175474E89094C44Da98b954EedeAC495271d0F': 1.0160205022039905,
'0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2': 731.8084019968687,
'0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48': 1,
'0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599': 11295.798587465093,
'0x04Fa0d235C4abf4BcF4787aF4CF447DE572eF828': 5.639471830426497,
'0x514910771AF9Ca656af840dff83E8264EcF986CA': 17.190539686741662,
'0x80fB784B7eD66730e8b1DBd9820aFD29931aab03': 0.4144812763717841,
'0x960b236A07cf122663c4303350609A66A7B288C0': 7.24429556748338, …
```

Restore coingecko

---

src/components/Modal/About.vue
src/components/Topnav.vue
src/components/Ui/Button.vue
src/style.scss

Add about modal and fix alignement on small buttons (unlock)

Add about modal

---

src/components/Modal/AddLiquidity.vue

add message for sXMR tx fail

---

src/components/List/Pool.vue
src/components/PoolBoxes.vue

Fix pool liquidity

---

src/_balancer/pool.ts
src/views/Pool/About.vue

Fixes # .
- Display block time parameters on the About tab

Display block time parameters

---

src/_balancer/pools.json

Bankless smart pool

---

src/components/Topnav.vue
src/store/modules/web3.ts

https://linear.app/balancer/issue/BAL-286

Fix login status not appear in topnav

---

src/components/Avatar.vue
src/components/List/Pool.vue
src/components/List/Token.vue
src/components/Modal/AddLiquidity.vue
src/components/Modal/SelectToken.vue
src/components/PoolOverview.vue
src/helpers/utils.ts
src/style.scss
src/views/Pool/Swaps.vue

https://linear.app/balancer/issue/BAL-289

Shorten long symbols

---

src/components/Modal/AddLiquidity.vue
src/views/Create.vue

Fix: https://linear.app/balancer/issue/BAL-287

Show checkbox warning only if form is valid

---

public/index.html
src/App.vue
src/helpers/fathom.ts
src/helpers/subgraph.ts
src/main.ts
src/store/modules/broadcast.ts

https://linear.app/balancer/issue/BAL-294

Add Fathom goals

---

src/_balancer/pools.json

Add PieDAO Defi++ pool

---

src/helpers/miningFactors.ts
src/helpers/tokens.ts
src/locales/en-US.json
src/views/Pool/About.vue

- Calculates and shows liquidity mining factors on About page

Show liquidity mining factors on About page

---

src/components/Modal/Wrapper.vue
src/helpers/miningFactors.ts
src/helpers/tokens.ts
src/locales/en-US.json
src/views/Pool/About.vue

This PR include the fix for ETH in the wrapper #203

New release to master

---

src/config/homestead.json
src/config/kovan.json

Switching to Infura seems to fix the issue.

Quick fix: Cloudflare data is stale

---

src/views/Pool/About.vue

- Show the year in the time display for gradual updates (About tab)

Add year to gradual update notices (per user request)

---

src/components/Chart.vue

- Avoids "sideways" artistic charting when swaps are too close together

Smooth out LBP price chart

---

.github/workflows/pinata-deploy.yml
vue.config.js

Adds github workflow to deploy to Pinata which will be used as backup host.
Also a slight change to build to make links Pinata friendly with relevant ENV set.

Added workflow to deploy on Pinata.

---

src/views/Pool/About.vue

- Factors that require tokens display NaN for dead pools
- Detect this and show "N/A (no tokens"

Don't display NaN factor values on dead pools

---

src/components/Modal/AddLiquidity.vue

Revert this PR https://github.com/balancer-labs/pool-management-vue/pull/243
This introduced an issue on adding liquidity for this pool: https://pools.balancer.exchange/#/pool/0x78c281090399ebc2d720595654b908ed31cd8bcb

Revert #243

---

src/components/Modal/AddLiquidity.vue

Merge to master revert #243

---

package-lock.json
package.json

Update walletconnect to v1.5.2
